name: Testes Github

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-tests-Modelo-Blackbox:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os: [ubuntu-latest]
        browser: [chrome]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run end-to-end black box tests 🧪
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
          CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        with:
          command: npm run cypress:run
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/Artefacts/*.mp4
  cypress-tests-Modelo-Whitebox:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm install
      - name: Run white box tests 🧪
        uses: cypress-io/github-action@v5
        with:
          command: npm run jest